import type { Person, CreditCard, ExpenseCategory, Transaction, Invoice } from "./types"

export const people: Person[] = [
  { id: "1", name: "João Silva", email: "joao@email.com", color: "#10b981" },
  { id: "2", name: "Maria Santos", email: "maria@email.com", color: "#3b82f6" },
  { id: "3", name: "Pedro Costa", email: "pedro@email.com", color: "#f59e0b" },
  { id: "4", name: "Ana Oliveira", email: "ana@email.com", color: "#ec4899" },
]

export const creditCards: CreditCard[] = [
  {
    id: "1",
    name: "Nubank",
    lastDigits: "4532",
    brand: "mastercard",
    limit: 15000,
    closingDay: 1,
    dueDay: 8,
    color: "#8b5cf6",
  },
  {
    id: "2",
    name: "Itaú Platinum",
    lastDigits: "7891",
    brand: "visa",
    limit: 25000,
    closingDay: 15,
    dueDay: 22,
    color: "#f97316",
  },
  {
    id: "3",
    name: "Inter",
    lastDigits: "2468",
    brand: "mastercard",
    limit: 10000,
    closingDay: 5,
    dueDay: 12,
    color: "#22c55e",
  },
  {
    id: "4",
    name: "C6 Bank",
    lastDigits: "3579",
    brand: "visa",
    limit: 8000,
    closingDay: 10,
    dueDay: 17,
    color: "#1f2937",
  },
]

export const categories: ExpenseCategory[] = [
  { id: "1", name: "Alimentação", icon: "utensils", color: "#f59e0b" },
  { id: "2", name: "Transporte", icon: "car", color: "#3b82f6" },
  { id: "3", name: "Lazer", icon: "gamepad", color: "#ec4899" },
  { id: "4", name: "Saúde", icon: "heart", color: "#ef4444" },
  { id: "5", name: "Educação", icon: "book", color: "#8b5cf6" },
  { id: "6", name: "Compras", icon: "shopping-bag", color: "#10b981" },
  { id: "7", name: "Assinaturas", icon: "repeat", color: "#6366f1" },
  { id: "8", name: "Casa", icon: "home", color: "#14b8a6" },
]

export const transactions: Transaction[] = [
  {
    id: "1",
    description: "iFood - Jantar",
    amount: 89.9,
    date: "2026-01-05",
    cardId: "1",
    personId: "1",
    categoryId: "1",
  },
  {
    id: "2",
    description: "Uber - Trabalho",
    amount: 32.5,
    date: "2026-01-05",
    cardId: "1",
    personId: "2",
    categoryId: "2",
  },
  {
    id: "3",
    description: "Netflix",
    amount: 55.9,
    date: "2026-01-03",
    cardId: "2",
    personId: "1",
    categoryId: "7",
    installments: 1,
    currentInstallment: 1,
  },
  {
    id: "4",
    description: "Mercado Livre - Fone",
    amount: 459.0,
    date: "2026-01-02",
    cardId: "1",
    personId: "3",
    categoryId: "6",
    installments: 3,
    currentInstallment: 1,
  },
  {
    id: "5",
    description: "Farmácia - Remédios",
    amount: 156.8,
    date: "2026-01-04",
    cardId: "3",
    personId: "4",
    categoryId: "4",
  },
  { id: "6", description: "Cinema", amount: 78.0, date: "2026-01-06", cardId: "2", personId: "2", categoryId: "3" },
  { id: "7", description: "Gasolina", amount: 250.0, date: "2026-01-07", cardId: "4", personId: "1", categoryId: "2" },
  {
    id: "8",
    description: "Curso Udemy",
    amount: 27.9,
    date: "2026-01-01",
    cardId: "1",
    personId: "3",
    categoryId: "5",
  },
  {
    id: "9",
    description: "Restaurante",
    amount: 189.0,
    date: "2026-01-06",
    cardId: "2",
    personId: "4",
    categoryId: "1",
  },
  {
    id: "10",
    description: "Amazon Prime",
    amount: 14.9,
    date: "2026-01-01",
    cardId: "3",
    personId: "1",
    categoryId: "7",
  },
  {
    id: "11",
    description: "Supermercado",
    amount: 523.45,
    date: "2026-01-04",
    cardId: "1",
    personId: "2",
    categoryId: "1",
  },
  { id: "12", description: "Spotify", amount: 21.9, date: "2026-01-01", cardId: "4", personId: "3", categoryId: "7" },
]

export const invoices: Invoice[] = [
  { id: "1", cardId: "1", month: 1, year: 2026, totalAmount: 1186.15, dueDate: "2026-01-08", status: "open" },
  { id: "2", cardId: "2", month: 1, year: 2026, totalAmount: 322.9, dueDate: "2026-01-22", status: "open" },
  { id: "3", cardId: "3", month: 1, year: 2026, totalAmount: 171.7, dueDate: "2026-01-12", status: "paid" },
  { id: "4", cardId: "4", month: 1, year: 2026, totalAmount: 271.9, dueDate: "2026-01-17", status: "open" },
]
